name: Game Compatibility
description: Report a game's compatibility status on shadPS4
body:
  - type: markdown
    attributes:
      value: |
         ## Important: Read First
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I've tested on the [latest major release](https://github.com/shadps4-emu/shadPS4/releases/latest) and not on a nightly build (In this case 0.11.0 and NOT 0.11.1 WIP).
          required: true
        - label: My report is made on an officially released PlayStation 4 game. (You can find a list of official PlayStation 4 games [here](https://www.serialstation.com/games/?systems=97ec53a2-f676-4c89-8172-e653dce5eed1))
          required: true
        - label: I've made sure there are no other issues opened for this game and operating system combo.
          required: true
        - label: My game dump comes from a copy of the game I own.
          required: true
        - label: My game dump is unmodified, I haven't enabled any game patches and I didn't repackage my game dump to a FPKG.
          required: true
        - label: I've dumped my PlayStation 4's firmware libraries, and placed all that the [compatibility list description](https://github.com/shadps4-compatibility/shadps4-game-compatibility?tab=readme-ov-file#information) mentions in the shadPS4 'sys_modules' folder.
          required: true
        - label: I've made sure my logging type is set to "sync" and not "async".
          required: true
        - label: I did not manually enable any settings that would change emulation behavior (such as "isPS4Pro", "isDevKit", "Vblank Frequency" etc).
          required: true          
           
  - type: input
    id: game-name
    attributes:
      label: Game Name
      placeholder: "Game Name"
    validations:
      required: true

  - type: input
    id: game-serial
    attributes:
      label: Game serial
      placeholder: "e.g. CUSA10005"
    validations:
      required: true

  - type: input
    id: game-version
    attributes:
      label: Game version
      placeholder: "e.g. v01.00"
    validations:
      required: true

  - type: input
    id: emulator-version
    attributes:
      label: Used emulator's version (only major released versions are acceptable)
      placeholder: "e.g v0.11.0"
    validations:
      required: true

  - type: dropdown
    id: emulation-status
    attributes:
      label: Current status
      options:
        - Nothing
        - Boots
        - Menus
        - Ingame
        - Playable
    validations:
      required: true

  - type: dropdown
    id: Operating-System
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: textarea
    id: emulation-error
    attributes:
      label: Error
      placeholder: Don't describe what is happening but copy and paste the error in the last lines of log (Often it starts with [Debug] <Critical>)
    validations:
      required: false

  - type: textarea
    id: emulation-description
    attributes:
      label: Description
      placeholder: What can you see, if the sound is good, graphics, glitches, etc ...
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Add screenshots here (preferably on windowed mode) if the game is rendering.
      placeholder: Drag and drop the images/screenshots onto the text area.
    validations:
      required: false

  - type: textarea
    id: log
    attributes:
      label: Log File
      description: Log files can be found in the user/log folder. Make sure the logging type is set to "sync" in the emulator settings.
      placeholder: Drag and drop the log file onto the text area.
    validations:
      required: true
