name: Update Compatibility Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Compatibility Data
        run: |
          BASE_URL="https://api.github.com/repos/shadps4-emu/shadps4-game-compatibility/issues"
          PER_PAGE=100
          PAGE=1
          COMPATIBILITY_DATABASE=$(jq -n '{}')

          fetch_all_issues() {
            while :; do
              echo "Fetching page $PAGE..."
              curl -s -D headers.txt -o body.json "${BASE_URL}?per_page=${PER_PAGE}&page=${PAGE}"

              if ! jq empty body.json > /dev/null 2>&1; then
                echo "Invalid JSON response from GitHub:"
                cat body.json
                exit 1
              fi

              ITEM_COUNT=$(jq 'length' body.json)
              if [ "$ITEM_COUNT" -eq 0 ]; then
                echo "No items returned, stopping."
                break
              fi

              for issue in $(jq -r '.[] | @base64' body.json); do
                _jq() {
                  echo "$issue" | base64 --decode | jq -r "$1"
                }

                TITLE=$(_jq '.title')
                ISSUE_NUMBER=$(_jq '.number')
                UPDATED_AT=$(_jq '.updated_at')
                MILESTONE=$(_jq '.milestone')

                if [ "$MILESTONE" == "null" ]; then
                  VERSION="unknown"
                else
                  VERSION=$(echo "$MILESTONE" | jq -r '.title // "unknown"')
                fi

                LABELS=$(_jq '.labels | map(.name) | .[]')

                if [[ "$TITLE" =~ (CUSA[0-9]{5}) ]]; then
                  CUSA_ID="${BASH_REMATCH[1]}"
                  OS_TYPE="os-unknown"
                  STATUS="status-unknown"

                  for label in $LABELS; do
                    [[ "$label" == os-* ]] && OS_TYPE="$label"
                    [[ "$label" == status-* ]] && STATUS="$label"
                  done

                  COMPATIBILITY_OBJ=$(jq -n \
                    --arg issue_number "$ISSUE_NUMBER" \
                    --arg last_tested "$UPDATED_AT" \
                    --arg status "$STATUS" \
                    --arg version "$VERSION" \
                    '{
                      issue_number: $issue_number,
                      last_tested: $last_tested,
                      status: $status,
                      version: $version
                    }')

                  COMPATIBILITY_DATABASE=$(echo "$COMPATIBILITY_DATABASE" | jq \
                    --arg CUSA_ID "$CUSA_ID" \
                    --arg OS_TYPE "$OS_TYPE" \
                    --argjson COMPATIBILITY_OBJ "$COMPATIBILITY_OBJ" \
                    'if .[$CUSA_ID] then .[$CUSA_ID] += {($OS_TYPE): $COMPATIBILITY_OBJ} else . + {($CUSA_ID): {($OS_TYPE): $COMPATIBILITY_OBJ}} end')
                fi
              done

              if ! grep -qi 'rel="next"' headers.txt; then
                echo "No more pages."
                break
              fi

              PAGE=$((PAGE + 1))
            done

            echo "$COMPATIBILITY_DATABASE" > compatibility_data.json
          }

          fetch_all_issues

      - name: Verify Compatibility Data file size
        run: |
          FILE_SIZE=$(stat -c %s compatibility_data.json)
          MAX_FILE_SIZE=307200  # 300 KB

          if [ "$FILE_SIZE" -lt "$MAX_FILE_SIZE" ]; then
            echo "Compatibility data file is too small ($FILE_SIZE bytes), skipping release creation."
            exit 0
          else
            echo "Compatibility data file is valid ($FILE_SIZE bytes). Proceeding."
          fi

      - name: Delete all releases and tags
        run: |
          TOKEN="${{ secrets.SHADPS4_TOKEN_COMPATIBILITY }}"
          REPO="${{ github.repository }}"

          RELEASES=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/$REPO/releases)
          for release_id in $(echo "$RELEASES" | jq -r '.[].id'); do
            echo "Deleting release ID $release_id"
            curl -s -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/releases/$release_id"
          done

          TAGS=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/$REPO/tags)
          for tag in $(echo "$TAGS" | jq -r '.[].name'); do
            echo "Deleting tag $tag"
            curl -s -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/git/refs/tags/$tag"
          done

      - name: Create a GitHub Release and Upload Data
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          RELEASE_NAME="shadps4-game-compatibility"  # Fixed name for the release
          BODY="Compatibility data update"

          RESPONSE=$(curl -s \
            -H "Authorization: token ${{ secrets.SHADPS4_TOKEN_COMPATIBILITY }}" \
            -X POST \
            -d '{
                  "tag_name": "'"$TAG_NAME"'",
                  "target_commitish": "main", 
                  "name": "'"$RELEASE_NAME"'",
                  "body": "'"$BODY"'",
                  "draft": false,
                  "prerelease": false
                }' \
            https://api.github.com/repos/${{ github.repository }}/releases)

          # Extract the ID of the created release
          RELEASE_ID=$(echo "$RESPONSE" | jq -r .id)

          # Upload the data file to the release
          curl -s \
            -H "Authorization: token ${{ secrets.SHADPS4_TOKEN_COMPATIBILITY }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @compatibility_data.json \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=compatibility_data.json"
